{{- if or .Values.additionalScrapeConfigs.createDefault }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus.additionalConfig.defaultSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.additionalScrapeConfigs.file }}: {{ include "prometheus.additionalConfig.scrapeConfig" . | b64enc | quote }}
{{- end }}
