{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "common.names.fullname" . }}
                port: 
                  number: {{ .Values.service.port }}
            {{- if and .Values.ingress.prefix (ne .Values.ingress.prefix "/") }}
            pathType: ImplementationSpecific
            path: {{ .Values.ingress.prefix }}(/|$)(.*)
            {{- end }}
{{- end -}}
