USER-SUPPLIED VALUES:
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install -n kube-system -f helm-values/ingress-nginx.yaml ingress-nginx ingress-nginx/ingress-nginx --atomic --timeout 1m
controller:
  kind: DaemonSet
  hostPort:
    enabled: true
    ports:
      http: 8080
      https: 8443
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
defaultBackend:
  enabled: true
  resources:
    limits:
      cpu: 20m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
