USER-SUPPLIED VALUES:
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install -n kube-system -f helm-values/ingress-nginx.yaml ingress-nginx ingress-nginx/ingress-nginx --atomic --timeout 1m
controller:
  hostNetwork: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: lichuan.guru/role
            operator: In
            values:
            - loadbalancer
